repos:
  # =========================================================
  # 🖤 Black - Code Formatter
  # =========================================================
  - repo: https://github.com/psf/black
    rev: 23.11.0  # Matches your requirements-dev.txt
    hooks:
      - id: black
        language_version: python3.10  # Match your AWS/local Python version
        args: [--line-length=88]  # Standard Black config

  # =========================================================
  # 🔀 isort - Import Sorter (Black compatible)
  # =========================================================
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black, --line-length=88]

  # =========================================================
  # 🧹 flake8 - Linter (style and syntax)
  # =========================================================
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]  # Black-compatible

  # =========================================================
  # 🧼 Pre-Commit Utility Hooks
  # =========================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files  # Warn for large model/data files

  # =========================================================
  # 🔍 mypy - Static Type Checker (for stricter type safety)
  # =========================================================
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic==1.10.13
          - sqlalchemy==2.0.23
          - fastapi==0.103.2
        args:
          [
            --ignore-missing-imports,
            --disable-error-code=attr-defined,
            --no-warn-unused-ignores,
          ]

default_language_version:
  python: python3.10  # Match runtime version everywhere
